# Deep Learning Book: Linear Algebra

Linear algebra is a branch of mathematics that is widely used throughout science and engineering. A good understanding of linear algebra is essential for understanding and working with many machine learning algorithms, especially deep learning algorithms. If you have previous experience with these concepts but need a detailed reference sheet to review key formulas, see [The Matrix CookBook](http://www2.imm.dtu.dk/pubdb/views/edoc_download.php/3274/pdf/imm3274.pdf). For full book about linear algebra - [Shilov 1977 linear algebra](https://cosmathclub.files.wordpress.com/2014/10/georgi-shilov-linear-algebra4.pdf)

The chapter is divided into following sections and subsections

* Scalars, Vectors, Matrices and Tensors 
* Multiplying Matrices and Vectors 
* Identity and Inverse Matrices 
* Linear Dependence and Span 
* Norms 
* Special Kinds of Matrices and Vectors 
* Eigendecomposition 
* Singular Value Decomposition (SVD) 
* The Moore Penrose Pseudoinverse 
* The Trace Operator 
* The Determinant 

### 1. Scalars, Vectors, Matrices, Tensors

The study of linear algebra involves several types of mathematical objects:


* A scalar is a single number
* A vector is an array of numbers of the same type (e.g. $x$ ∈ ℝ)
* A matrix is a 2-D array
* An array of numbers arranged in a regular grid with a variable number of axes is known as a tensor. The element at coordinates $(i, j, k)$ of a tensor $A$ is represented as $A_{i, j, k}$. To simplify atensor is a $n$-dimensional array with $n>2$.

![image](https://refactored.ai/track/python-for-machine-learning/images/linear-algebra1.png)

One important operation on matrices is thetranspose. The transpose of amatrix is the mirror image of the matrix across a diagonal line, called the main diagonal, running down and to the right, starting from its upper left corner. See figure below to understand it better

#### ![image](http://xaktly.com/Images/Mathematics/MatrixAlgebra/MatrixOperations/MatrixTranspose.png)

* With transposition you can convert a row vector to a column vector and vice versa:
* The transpose ${A}^{\text{T}}$ of the matrix  ${A}$ corresponds to the mirrored axes. 


In [3]:
import numpy as np
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
A_t = A.T
A_t

array([[1, 3, 5],
       [2, 4, 6]])

The addition of a matrix A and a vector b, yields another matrix: C= A+b, where C$_{i,j}$= A$_{i,j}$+b$_{j}$. In other words, the vector b is added to each row of the matrix. This shorthand eliminates the need to define a matrix with b copied into each row before doing the addition. This implicit copying of b to many locations is called <b>broadcasting.</b>

$$
\begin{bmatrix}
    A_{1,1}  &  A_{1,2} \\\\
    A_{2,1}  &  A_{2,2} \\\\
    A_{3,1}  &  A_{3,2}
\end{bmatrix}+
\begin{bmatrix}
    B_{1,1} \\\\
    B_{2,1} \\\\
    B_{3,1}
\end{bmatrix}
$$

is equivalent to

$$
\begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}+
\begin{bmatrix}
    B_{1,1} & B_{1,1} \\\\
    B_{2,1} & B_{2,1} \\\\
    B_{3,1} & B_{3,1}
\end{bmatrix}=
\begin{bmatrix}
    A_{1,1} + B_{1,1} & A_{1,2} + B_{1,1} \\\\
    A_{2,1} + B_{2,1} & A_{2,2} + B_{2,1} \\\\
    A_{3,1} + B_{3,1} & A_{3,2} + B_{3,1}
\end{bmatrix}
$$

Broadcasting is more than just a notation convenience. When using libraries such as numpy and Tensorflow, broadcasting can reduce the memory requirements of a program. [Broadcasting in Numpy](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html) has many examples and explainations for you to refer to.

In [9]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
B = np.array([[1], [2], [3]])
B

array([[1],
       [2],
       [3]])

In [11]:
# Broadcasting
C=A+B
C

array([[2, 3],
       [5, 6],
       [8, 9]])

### 2. Multiplying Matrices and Vectors

One of the most important operations involving matrices is multiplication of two matrices. The matrix product of matrices A and B is a third matrix C. For a matrix multiplication between two matrices $A_{mn}$ and $B_{kp}$ to exist, we must have $n == k$. The resulting matrix $C$ has the shape $m$ x $p$.

<b> Element-wise product</b> or <b> Hadamard Product </b> : $A \odot B$ <br>
<b> Dot Product </b> :  $x^Ty$ ($x$ and $y$ are of same dimension)

Some properties of matrix multiplication are:

* $A(B+C) = AB + AC$ (Distributive)
* $A(BC) = (AB)C$ (Associative)
* $AB \ne BA$ (not commutative, in general)
* $(AB)^T = B^TA^T$
* $x^Ty = (x^Ty)^T = y^Tx$

System of linear equation $ Ax = B $ can be written as 

$A_{i,1}x_1 + A_{i,2}x_2 + ... + A_{i,n}x_n = b_i$ <br>
where $A \in ℝ^{mxn}$ & $b \in ℝ^{m}$ are known and $x \in ℝ^{n}$ is to be found.

### 3. Identity and Inverse Matrices

Equation $ Ax = B $ can be solved analytically for many values of A using **Matrix Inversion**

An **identity matrix** is a matrix that does not change any vector when we multiply that vector by that matrix. The entries along its main diagonal is 1. All other entries are zero.

*Change the value in parantheses of the below code to take a look at n-dim identity matrix*

In [15]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

The **matrix inverse** of $A$ is denoted as $A^{-1}$ and is given by 
$$A^{-1}A = AA^{-1} = I_n$$

Now we can solve the equation $Ax = B$ using following steps

$$  Ax = b \\ 
A^{-1}Ax = A^{-1}b \\
I_nx = A^{-1}b \\ 
x = A^{-1}b \\
$$

### 4. Linear Dependence and Span

For $A^{-1}$ to exist, equation $Ax = B$ must have exactly one solution for every real value of $b$. The system can have zero or infinitely many solutions for some values of b, but can't have a finite number of solutions greater than one.

$$
A_{1,1}x_1 + A_{1,2}x_2 + \cdots + A_{1,n}x_n = b_1 \\\\
A_{2,1}x_1 + A_{2,2}x_2 + \cdots + A_{2,n}x_n = b_2 \\\\
\cdots \\\\
A_{m,1}x_1 + A_{m,2}x_2 + \cdots + A_{m,n}x_n = b_n
$$

So we have multiple equations with multiple unknowns. We know $A_{1,1}...A_{m,n}$ and $b_1...b_n$. To solve the system we need to find the values of the variables $x_1...x_n$ that satisfies all equations.

#### Why there can't be more than 1 solution and less than an infinite number of solutions ?

This is because we deal with **linear** systems! Two lines can't cross more than once. For visualization, let's take two dimensions and two equations. The solutions of the system correspond to the intersection of the lines. One option is that the two lines never cross (parallel). Another option is that they cross once. And finally, the last option is that they cross everywhere (superimposed). Two lines can't cross each other more than once

![image](https://8thgradevocabbook.weebly.com/uploads/1/6/9/6/16969092/864202982_orig.gif)

#### Linear Combination

Formally, a linear combination of some set of vectors ${v(1), . . . , v(n)}$ is given by multiplying each vector $v(i)$ by a corresponding scalar coefficient and adding the results. The equation $Ax$ can be represented using matrix as

$$ Ax = \begin{bmatrix} {A_{1,1}x_1 + A_{1, 2}x_2 + ... A_{1, n}x_n} \\ {A_{2,1}x_1 + A_{2, 2}x_2 + ... A_{2, n}x_n } \\ . \\ . \\ . \\ {A_{m,1}x_1 + A_{m, 2}x_2 + ... A_{m, n}x_n} \end{bmatrix} $$
Which can also be written as: $$ \begin{bmatrix} {A_{1,1}x_1 + A_{1, 2}x_2 + ... A_{1, n}x_n} \\ {A_{2,1}x_1 + A_{2, 2}x_2 + ... A_{2, n}x_n } \\ . \\ . \\ . \\ {A_{m,1}x_1 + A_{m, 2}x_2 + ... A_{m, n}x_n} \end{bmatrix} = x_1 \begin{bmatrix} A_{1,1} \\ A_{2,1}\\ . \\ . \\ . \\ A_{m,1}  \end{bmatrix} + x_2 \begin{bmatrix} A_{1,2} \\ A_{2,2}\\ . \\ . \\ . \\ A_{m,2}  \end{bmatrix} + ... x_n \begin{bmatrix} A_{1,n} \\ A_{2,n}\\ . \\ . \\ . \\ A_{m,n}  \end{bmatrix} = \sum_{i=1}^{n} x_iA_{:, i}$$

Which corresponds to the set of linear equations
$$
A_{1,1}x_1 + A_{1,2}x_2 + \cdots + A_{1,n}x_n = b_1 \\\\
A_{2,1}x_1 + A_{2,2}x_2 + \cdots + A_{2,n}x_n = b_2 \\\\
\cdots \\\\
A_{m,1}x_1 + A_{m,2}x_2 + \cdots + A_{m,n}x_n = b_n
$$


Thus: $$ Ax = \sum_{i=1}^{n} x_iA_{:, i}  $$

Where $A_{:, i}$ is the $i^{th}$ column of $A$. This kind of operation is called a **linear combination**

The **span** of a set of vectors is the set of all points obtainable by linear combination of the original vectors. Determining whether $Ax=b$ has a solution thus amounts to testing whether $b$ is in the span of the columns of $A$. This particular span is known as the column space, or the range, of A. The requirement that the column space of $A$ be all of $R^m$ implies immediately that $A$ must have at least $m$ columns, that is, $n ≥ m$. Otherwise, the dimensionality of the column space would be less than $m$.

Having $n ≥ m$ is only a necessary condition for every point to have a solution.It is not a sufficient condition, because it is possible for some of the columns to be redundant.

Here, the concept of **linear dependency** is introduced. A set of vectors are linearly independent if none of the vectors is a linear combination of the other vectors. Thus, for the column space of $A$ to be all of $R^m$, it must contain atleast one set of m linearly independent columns. The system must have at most one solution for each value of $b$, hence, $A$ must have at most m columns, or else there are multiple ways of parameterizing each solution.

Together, this means that the matrix must be square, that is, we require that $m=n$ and that all the columns be linearly independent. A square matrix with linearly dependent columns is known as **singular**.

If $A$ is not square yet singular, it's still possible to solve the equation, but we cannot use the method of matrix inversion for it.

### 5. Norms

The size of a vector is given by functions called **norms**.Here is the recipe to get the $p$-norm of a vector:

* Calculate the absolute value of each element
* Take the power $p$ of these absolute values
* Sum all these powered absolute values
* Take the power $\frac{1}{p}$ of this result

Most commonly used, the $L^p$ norm given by:

$$ ||\mathbf{x}||_p = (\sum_{i} |x_i|^p)^{\frac{1}{p}} $$

A norm function $f$ satisfies the following properties:

$f(x) = 0 \Rightarrow x = 0$<br>
$f(x+y) \leq f(x) + f(y)$ (The triangle inequality)<br>
$\forall \alpha \in ℝ, \hspace{.1cm} f(\alpha x) = |\alpha|f(x)$

#### Types of norms

* Euclidean Norm: This is the $L^2$ norm, which is heavily used in machine learning, and can be also calculated as $x^Tx$. 
The $L^2$ norm can be calculated with the *linalg.norm* function from numpy. We can check the result:

In [5]:
np.linalg.norm([3, 4])

5.0

In this case, the vector is in a 2-dimensional space but this stands also for more dimensions.

$$
u=
\begin{bmatrix}
    u_1\\\\
    u_2\\\\
    \cdots \\\\
    u_n
\end{bmatrix}
$$$$
||u||_2 = \sqrt{u_1^2+u_2^2+\cdots+u_n^2}
$$

* L1 Norm: It is used when the difference between the zero and non-zero elements is very important.
* Max Norm (also known as the $L^{\infty}$ norm): Absolute value of the largest magnitude in the vector: $||x||_{\infty} = \displaystyle \max_{i}|x_i|$
* Frobenius Norm: Used to measure the size of a matrix (similar to the $L^2$ norm): $||A||_F = \sqrt{\displaystyle \sum_{i,j} A_{i,j}^2} $

### 6. Special Kinds of Matrices and Vectors

Some special kinds of matrices and vectors are particularly useful

**Diagonal Matrices:** A matrix $D$ is diagonal if and only if $Di,j= 0$ for all i =/=j. e.g. Identity Matrix.
* A square diagonal matrix can be represented as: $diag(v)$ where the vector $v$ represents the elements along tha main diagonal.
* Multiplying by a diagonal matrix is computationally efficient. $Dx$ can be calculated by simply scaling each $x_i$ by $v_i$.
* A diagonal matrix need not be square

**Symmetric Matrix** : $A = A^T$

**Unit Vector**: A vector with **unit norm**  $||x||_2 = 1$.

**Orthogonal vectors:** Two vectors $x$ and $y$ are orthogonal if $x^Ty = 0$, which means that if both of them have non-zero norm, these vectors are at a 90 degree angle to each other. **Orthogonal vectors having unit norm are called orthonormal vectors.**

**Orthogonal Matrix**: A matrix whose rows are mutually orthonormal (and columns too). Thus: $$ A^TA = AA^T = I $$$$\Rightarrow A^{-1} = A^T $$ 


### 7. Eigendecomposition

**Eigen-decomposition** decompose a matrix into a set of **eigenvectors** and **eigenvalues.** An eigenvector of a square matrix $A$ is a non-zero vector $v$ such that multiplication by $A$ alters only the scale of $v$:
$$ Av = \lambda v $$
The scalar $\lambda$ is called the eigenvalue corresponding to the eigenvector. Any scaled version of an eigenvector is also an eigenvector with the same eigenvalue, hence we focus on only unit eigenvectors.

The eigendecomposition of a matrix $A$, having $n$ linearly independent eigenvectors represented as a matrix $V = [v^{(1)}, ... , v^{(n)}]$ with the corresponding eigenvalues given by the vector $\lambda = [\lambda_1, ... , \lambda_n]$ is given by:

$$ A = Vdiag(\lambda)V^{-1} $$

![image](https://www.simplilearn.com/ice9/free_resources_article_thumb/effect-of-eigenvalue-and-eigenvectors.JPG)

### 8. Singular Value Decomposition (SVD)

The **singular value decomposition(SVD)** provides another way to factorizea matrix, into singular vectors and singular values. The SVD enables us to discover some of the same kind of information as the eigen-decomposition reveals;however, the SVD is more generally applicable.

For SVD, we represent $A$ as 
$$A = UDV^T $$


Suppose $A$ is an $mxn$ matrix. Then $U$ is defined to be an $mmn$ matrix, $D$ to be an $mxn$ matrix and $V$ to be an $nxn$ matrix.

The matrices $U$ and $V$ are both defined to be orthogonal matrices. Matrix $D$ is defined to be a diagonal matrix (not necessarily square). The elements along the diagonal of $D$ are known as the **singular values** ofthe matrix $A$. The columns of $U$ are known as the **left-singular vectors**. The columns of $V$ are known as as the **right-singular vector**.

### 9. . The Moore-Penrose Pseudoinverse

Suppose we want to make a left-inverse $B$ of a matrix $A(mxn)$ so that we can solve a linear equation
$$ Ax = y $$$$\Rightarrow x = By$$

We define the pseudoinverse of $A$ as:

$$A^+ = \lim\limits_{\alpha \rightarrow 0} (A^TA + \alpha I)^{-1}A^T$$
However, for practical algorithms its defined as:

$$ A^+ = VD^+U^T $$

where $U$,$D$ and $V$ are the singular value decomposition of $A$, and the pseudoinverse $D+$ of a diagonal matrix $D$ is obtained by taking the reciprocal of its non-zero elements then taking the transpose of the resulting matrix.

When m>n, it is possible for there to be no solution and $A^+$ gives the $x$ such that $Ax$ is as close to $y$ in terms of the Euclidean norm $||Ax - y||$.

When m<=n, using $A^+$, gives one of many possible solutions, with the minimal Euclidean norm:

$$ x = A^{+}y $$

### 10. The Trace Operator


The trace operator gives the sum of all the diagonal elements.

$$ Tr(A) = \sum_{i}A_{i,i}$$



$||A||_F = \sqrt{Tr(AA^T)} $ (Frobenius Norm)<br>
$Tr(A) = Tr(A^T)$ (Transpose Invariance)<br>
$Tr(ABC) = Tr(CAB) = Tr(BCA)$ <br>( If the shapes of corresponding matrices allow it)


### 11. The Determinant### 


The determinant of a square matrix (denoted by $det(A)$) maps matrices to real scalars. It is equal to the product of all the eigenvalues of the matrix. It denotes how much multiplication by the matrix expands or contracts space. If the value is 0, then space is contracted completely atleast along one dimension causing it to lose all its volume. If the value is 1, then the transformation preserves volume.

### 12. Principal Component Analysis

I've explained PCA in detail [here](https://medium.com/@the_change/principal-component-analysis-explained-560df8832b93)